import { PageLayout, Callout } from '../components';
import styles from './Tech.module.css';

export function Tech() {
  return (
    <PageLayout narrow>
      <h1 className={styles.title}>Technology</h1>
      <p className={styles.intro}>
        At a high level, LLMs and generative media enable the mass production of convincing text, images, and video. That changes the scale and ease of creating misleading content. Two further issues make the problem harder: biased or low-quality sources in the training data, and the risk of a feedback loop where generated content pollutes the pool of information that future models learn from.
      </p>

      <section aria-labelledby="scale-heading">
        <h2 id="scale-heading" className={styles.heading}>
          Scale and ease
        </h2>
        <p>
          Classic misinformation required human effort to write, edit, and distribute. Today, synthetic or AI-assisted content can be produced in large volume with minimal cost. That makes it easier to flood information environments, target many communities at once, and adapt messages quickly. The same technology can support legitimate uses (e.g. summarisation, translation), so the challenge is to address misuse without blocking beneficial applications.
        </p>
      </section>

      <section aria-labelledby="sources-heading">
        <h2 id="sources-heading" className={styles.heading}>
          Biased and low-quality sources
        </h2>
        <p>
          Models are trained on data scraped from the open web and other corpora. Those sources can be biased, outdated, or deliberately manipulated. Without careful curation and transparency, generated content can reproduce and amplify those biases or errors. For journalism and public discourse, that means AI-assisted outputs may look authoritative while encoding systematic inaccuracies or skewed perspectives.
        </p>
      </section>

      <Callout
        variant="warning"
        title="Key weakness"
      >
        <p style={{ margin: 0 }}>
          <strong>Online info pool → generated content → training loop.</strong> Content generated by AI is increasingly re-absorbed into the datasets used to train the next generation of models. That creates a feedback loop: errors and biases in today's outputs can become “facts” in future training data, degrading the quality and reliability of the information ecosystem over time.
        </p>
      </Callout>
    </PageLayout>
  );
}
